version: "3.0"
services:
  redis:
    #
    # TODO bind to local port only
    image: redis:latest
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
  streaming:
    image: orcasound/orcanode:arm32v7
    command: ["sh", "-c", "sleep 2073600"]
#    command: ./stream.sh
    restart: always
    env_file: .env
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
     - ./audio:/audio
    build:
      context: .
      dockerfile: Dockerfile
  inotify:
    image: orcasound/orcanode:arm32v7
#    command: ["sh", "-c", "sleep 2073600"]
#    command: bash -c "./upload_rq_s3.py && ./failed_rq_s3.py"
    command: bash -c "./upload_rq_s3.py" 
    restart: always
    env_file: .env
    privileged: true
    volumes:
     - ./audio:/audio
     - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    depends_on:
      - redis
      - streaming
  worker:
    image: orcasound/orcanode:arm32v7
    command: rq worker high medium low -u 'redis://redis:6379'
    restart: always
    env_file: .env
    privileged: true
    volumes:
     - ./audio:/audio
    depends_on:
     - inotify
  logspout:
    # Use unofficial logspout that's been compiled for armhf
    # TODO: Build an updated version of this image. Looks unmaintained.
    image: emdem/raspi-logspout
    command: ${SYSLOG_URL}
    restart: always
    hostname: ${NODE_NAME}
    env_file: .env
    environment:
      - SYSLOG_HOSTNAME=${NODE_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    
