version: "3"
services:
  streaming:
    # (temporary) skip the image name so that any previously pulled image doesn't get overwritten
    #image: orcasound/orcanode:arm32v7
    build: ./
    command: ./stream.sh
    restart: always
    env_file: .env
    ports:
      - "1234:1234"
      - "8080:8080"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true

  logspout:
    # Use unofficial logspout that's been compiled for armhf
    # TODO: Build an updated version of this image. Looks unmaintained.
    image: emdem/raspi-logspout
    command: ${SYSLOG_URL}
    restart: always
    hostname: ${NODE_NAME}
    env_file: .env
    environment:
      - SYSLOG_HOSTNAME=${NODE_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
