version: "3"
services:
  streaming:
    image: orcasound/orcanode
    build: ./
    command: ./stream.sh
    restart: always
    env_file: .env
    ports:
      - "1234:1234"
      - "8080:8080"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true