name: dockerized tests

on:
  push:
    branches:
      - master
      - mseed
  pull_request:
    branches:
      - master
      - mseed

  
jobs:
  Docker-build-and-push:
    runs-on: ubuntu-20.04
    steps:  
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push base
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./base/amd64/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/orcabase:latest
      
      - name: Build and push mseed
        id: docker_build_mseed
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./mseed/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/orcamseed:latest

  Docker-container:
    needs: Docker-build-and-push
    runs-on: ubuntu-20.04
    steps: 
      - name: start containers
        uses: addnab/docker-run-action@v3
        env: 
          AWSACCESSKEYID: ${{ secrets.AWSACCESSKEYID }}
          AWSSECRETACCESSKEY: ${{ secrets.AWSSECRETACCESSKEY }}
          TIME_PREFIX: ${{ secrets.TIME_PREFIX }}
          DELAY_SEGMENT: ${{ secrets.DELAY_SEGMENT }}
          NODE_NAME: ${{ secrets.NODE_NAME }}
          NODE_LOOPBACK: ${{ secrets.NODE_LOOPBACK}}
          ENV: ${{ secrets.ENV }}        
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: karan2704/orcamseed:latest
          options: -v ${{ github.workspace }}:/root
          run: ls && python3 ooipypull.py


       
      - name: clean up containers
        run: docker kill $(docker ps -q)

